In [25]:
import numpy as np

In [60]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
C = np.column_stack((A, B.T))

rankA = np.linalg.matrix_rank(A, 0.0001)
rankC = np.linalg.matrix_rank(C, 0.0001)

print(C)
print(f'{rankA} < {rankC}, следовательно СЛАУ решений не имеет') if rankA < rankC else print('')

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
2 < 3, следовательно СЛАУ решений не имеет


In [61]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([0, 0, 0])
C = np.column_stack((A, B.T))

rankA = np.linalg.matrix_rank(A, 0.0001)
rankC = np.linalg.matrix_rank(C, 0.0001)

print(C)
print(f'{rankA} = {rankC}, следовательно СЛАУ имеет бесконечное множество решений') if rankA == rankC else print('')

[[1 2 3 0]
 [4 5 6 0]
 [7 8 9 0]]
2 = 2, следовательно СЛАУ имеет бесконечное множество решений
