In [1]:
import numpy as np
import scipy
import scipy.linalg

In [16]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print('P', P)
print('')
print('L', L)
print('')
print('U', U)
print('')

print(np.dot(np.linalg.inv(P), A) - np.dot(L, U))

P [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

L [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

U [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
print(f'detA = {np.linalg.det(A)}')

P, L, U = scipy.linalg.lu(A)
A = np.dot(L, U)
B = np.array([4, 1, 7])
np.linalg.solve(A, B)

detA = 432.00000000000017


array([ 0.28240741,  0.70601852, -0.23148148])